config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/portfolio", to: "pages#portfolio"
  get "/nft", to: "pages#nft"
  get "/privacy", to: "pages#privacy"

  get "/transfers", to: "transfers#index"
  get "/transfers/new", to: "transfers#new"

  resources :wallets do
    resources :cryptos do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :wallet

  validates :name, presence: true
  validates :number, presence: true
  validates :number, numericality: { greater_than_or_equal_to: 0 }
  validates :account, presence: true

  SELECT_CRYPTO = CoinGeckoService.new.get_coin_options
end

app/models/transfer.rb
class Transfer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wallets
  has_many :tranfers
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :cryptos, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
  validates :category, presence: true

  SELECT_CATEGORY = ["Exchange", "Cold Wallet", "Hot Wallet"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home, :nft, :transaction, :privacy]
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  def new
    @crypto = Crypto.new
    @wallet = Wallet.find(params[:wallet_id])
    @select_cryptos = CoinGeckoService.new.search_for_crypto.map { |coin| coin["name"] }.sort    
  end

  def create
    @crypto = Crypto.new(crypto_params)
    @wallet = Wallet.find(params[:wallet_id])
    @crypto.wallet = @wallet
    if @crypto.save
      redirect_to wallet_path(@wallet)
    else
      render :new
    end
  end

  def edit
    @crypto = Crypto.find(params[:id])
    @wallet = Wallet.find(params[:wallet_id])
  end

  def update
    @crypto = Crypto.find(params[:id])
    @wallet = Wallet.find(params[:wallet_id])
    @crypto.update!(crypto__update_params)
    redirect_to wallet_path(@wallet)
  end

  def destroy
    @crypto = Crypto.find(params[:id])
    @wallet = Wallet.find(params[:wallet_id])
    @crypto.destroy
    redirect_to wallet_path(@wallet), notice: "You have well deleted this asset"
  end

  private

  def crypto_params
    params.require(:crypto).permit(:account, :name, :address, :number, :wallet_id)
  end

  def crypto__update_params
    params.require(:crypto).permit(:account, :address, :number, :wallet_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'net/http'
  require 'json'

  def home
    @coins = CoinGeckoService.new.get_coins_markets
    @select_cryptos = @coins.map { |coin| coin["name"] }.sort
  end

  def portfolio
    @search_cryptos = CoinGeckoService.new.get_coins_markets

    @wallets = Wallet.where(user: current_user)

    @portfolio_value = 0
    @number_of_crypto = 0
    @portfolio_value_change_24h = 0
    @portfolio_rows = []

    @wallets.each do |wallet|
      @number_of_crypto += wallet.cryptos.size
      wallet.cryptos.sort_by(&:name).each do |crypto|
        @search_crypto = @search_cryptos.find { |search_crypto| search_crypto["name"] == crypto.name }
        @crypto_current_price = @search_crypto["current_price"]
        @crypto_value = crypto.number.to_f * @crypto_current_price.to_f
        @portfolio_value += @crypto_value
      end

      wallet.cryptos.sort_by(&:name).each do |crypto|
        @search_crypto = @search_cryptos.find { |search_crypto| search_crypto["name"] == crypto.name }
        @crypto_current_price = @search_crypto["current_price"]
        @crypto_value = crypto.number.to_f * @crypto_current_price.to_f
        @crypto_change_24h = @search_crypto["price_change_percentage_24h"]
        @crypto_symbol = @search_crypto["symbol"]
        @crypto_logo = @search_crypto["image"]

        @value = crypto.number * @crypto_current_price
        @value_change_24h = (@value * @crypto_change_24h) / 100
        @portfolio_value_change_24h += @value_change_24h

        @portfolio_rows << {
          account: crypto.account,
          name: crypto.name,
          current_price: @crypto_current_price,
          allocation: (@value * 100) / @portfolio_value,
          wallet_name: wallet.name,
          number: crypto.number,
          value: @value,
          symbol: @crypto_symbol,
          image: @crypto_logo
        }
      end
    end
    @portfolio_rows.sort_by! { |row| -row[:value] }
  end

  def transaction
  end

  def nft
    @url = "https://api.rarible.org/v0.1/items/byOwner/?owner=ETHEREUM:#{params[:query]}"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @nfts = JSON.parse(@response)

    @wallets = Wallet.where(user: current_user)
  end

  def privacy
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  require 'httparty'

  def new
  end

  def index
    @wallets = Wallet.where(user: current_user)

    # Get the history of all transactions of an ethereum address
    response = HTTParty.get("https://api.etherscan.io/api?module=account&action=txlist&address=#{params[:query]}&startblock=0&endblock=99999999&sort=asc&apikey=#{ENV['API_KEY']}")
    @transactions = response.parsed_response['result']

    # Create a collection from all the ethereum addresses of the user
    @address_option = []
    @wallets.each do |wallet|
      wallet.cryptos.each do |crypto|
        @address_option.push(crypto.address) if crypto.name == "Ethereum"
      end
    end
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :search_for_crypto

  def index
    @wallets = Wallet.where(user: current_user)
  end

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = Wallet.new(wallet_params)
    @wallet.user = current_user
    if @wallet.save
      redirect_to wallet_path(@wallet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @crypto = Crypto.new
    @wallet = Wallet.find(params[:id])
    @select_cryptos = CoinGeckoService.new.search_for_crypto.map { |coin| coin["name"] }.sort
    @wallet_value = 0
    @number_of_crypto = @wallet.cryptos.size
    @wallet_value_change_24h = 0
    @wallet_rows = []

    @wallet.cryptos.each do |crypto|
      @search_crypto = @search_cryptos.find { |search_crypto| search_crypto["name"] == crypto.name }
      @crypto_current_price = @search_crypto["current_price"]
      @value = crypto.number * @crypto_current_price
      @wallet_value += @value
    end

    @wallet.cryptos.sort_by(&:name).each do |crypto|
      @search_crypto = @search_cryptos.find { |search_crypto| search_crypto["name"] == crypto.name }
      @crypto_current_price = @search_crypto["current_price"]
      @crypto_change_24h = @search_crypto["price_change_percentage_24h"]
      @crypto_symbol = @search_crypto["symbol"]
      @crypto_logo = @search_crypto["image"]
      @value = crypto.number * @crypto_current_price
      @value_change_24h = (@value * @crypto_change_24h) / 100
      @wallet_value_change_24h += @value_change_24h

      @wallet_rows << {
        account: crypto.account,
        name: crypto.name,
        current_price: @crypto_current_price,
        allocation: (@value * 100) / @wallet_value,
        number: crypto.number,
        value: @value,
        symbol: @crypto_symbol,
        image: @crypto_logo,
        address: crypto.address,
        wallet: crypto.wallet,
        crypto: crypto
      }
    end
    @wallet_rows.sort_by! { |row| -row[:value] }
  end

  def edit
    @wallet = Wallet.find(params[:id])
  end

  def update
    @wallet = Wallet.find(params[:id])
    @wallet.update!(wallet_params)
    redirect_to wallet_path(@wallet)
  end

  def destroy
    @wallet = Wallet.find(params[:id])
    @wallet.destroy
    redirect_to wallets_path, status: :see_other, notice: "You have well deleted this wallet"
  end

  private

  def wallet_params
    params.require(:wallet).permit(:name, :category)
  end

  def search_for_crypto
    @search_cryptos = CoinGeckoService.new.search_for_crypto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cryptos/edit.html.erb
<div class="form-container">
  <h1>EDIT CRYPTO</h1>
  <%= form_with model: [@wallet, @crypto] do |f| %>
  <div class="form-cellule mt-5">
    <%= f.text_field :account, placeholder: "Account", class: "form-button-input" %>
  </div>
  <div class="form-cellule mt-5">
    <div class="form-button-input">
      <%= @crypto.name %>
    </div>
  </div>
  <div class="form-cellule mt-5 mb-4">
    <%= f.text_field :address, placeholder: @crypto.address, class: "form-button-input" %>
  </div>
  <div class="form-cellule mt-5 mb-4">
    <%= f.number_field :number, placeholder: @crypto.number.to_s, class: "form-button-input", :step => 0.00000001 %>
  </div>
  <div>
    <%= f.submit class: "grey-button" %>
  </div>
  <% end %>
  <div class="p-2">
    <%= link_to "Delete crypto", wallet_crypto_path(@wallet), class: "small-button", data: {turbo_method: :delete, turbo_confirm: "Are yo sure to delete this crypto?"} %>
  </div>
</div>

app/views/cryptos/new.html.erb
<div class="form-container-small">
  <h1>NEW CRYPTO</h1>
  <%= form_with model: [@wallet, @crypto] do |f| %>
  <div class="form-cellule mt-5">
    <div class="form-cellule mt-5">
      <%= f.text_field :account, placeholder: "Account", class: "form-button-input" %>
    </div>
    <div>
      <%= f.select :name, @select_cryptos, class: "form-button-input" %>
    </div>
  </div>
  <div class="form-cellule mt-5">
    <%= f.text_field :address, placeholder: "Address", class: "form-button-input" %>
  </div>
  <div class="form-cellule mt-5">
    <%= f.number_field :number, placeholder: "Amount", class: "form-button-input", :step => 0.00000001 %>
  </div>
  <div>
    <%= f.submit "Add crypto", class: "grey-button"%>
  </div>
  <% end %>
</div>

app/views/pages/nft.html.erb
<div class="container">
  <div class="form-container">
    <h1>NFTs Collection</h1>
    <%= form_with url: nft_path, method: :get do |form| %>
    <div class="mt-5">
      <%= form.text_field :query, placeholder: "Address Ethereum", class: "form-button-input query-nfts" %>
    </div>
    <div class=" mt-2 mb-5">
      <%= form.submit "Enter", class: "grey-button" %>
    </div>
    <% end %>

    <% if params[:query].present? %>
      <% begin %>
        <% @nfts["items"].each do |nft| %>
        <div class="mt-5">
          <% if nft["meta"]["content"].first["url"].present? %>
            <img src="<%= nft["meta"]["content"].first["url"] %>" alt="" width="350px">
            <% if nft["meta"]["name"].present? %>
            <div class="color-medium-grey mt-2">
              <%= nft["meta"]["name"] %>
            </div>
            <% end %>
          <% end %>
        </div>
        <% end %>
      <% rescue => e %>
      <% end %>
    <% end %>

    <% @wallets.each do |wallet| %>
    <% wallet.cryptos.each do |crypto| %>
      <% if crypto.name == "Ethereum" || crypto.name == "Polygon"%>
        <% @url = "https://api.rarible.org/v0.1/items/byOwner/?owner=ETHEREUM:#{crypto.address}" %>
        <% @uri = URI(@url) %>
        <% @response = Net::HTTP.get(@uri) %>
        <% @nfts_from_wallet = JSON.parse(@response) %>
          <% if @nfts_from_wallet["items"].present? %>
            <div class="mt-5">
              <%= "NFTs ADDRESS:"%>
            </div>
            <div class="color-medium-grey mt-2">
              <%="#{crypto.address}" %>
            </div>
            <% @nfts_from_wallet["items"].each do |nft_from_wallet| %>
              <div class="mt-5">
              <% begin %>
                <% if nft_from_wallet["meta"]["content"].first["url"].present? %>
                  <img src="<%= nft_from_wallet["meta"]["content"].first["url"] %>" alt="" width="350px">
                  <div class="color-medium-grey mt-2">
                    <%= nft_from_wallet["meta"]["name"] %>
                  </div>
                <% end %>
              <% rescue => e %>
              <% end %>
              </div>
            <% end %>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/pages/portfolio.html.erb
<!-- print portfolio value and change 24h -->
<div class="container mb-3">
  <div class="container container-portfolio mb-4">
    <div class="card-cryptos-details">
      <h1 class="m-2">
        € <%= @portfolio_value.round(2).delimited(delimiter = ',') %>
      </h1>
      <h2 class="m-2">
        PORTFOLIO (<%= @number_of_crypto %>)
      </h2>
    </div>
    <div class="m-2 color-medium-grey">
      Total balance
    </div>
    <div class="m-2" >
    <% if @portfolio_value_change_24h > 0 %>
      <div class="text-success">
        +<%= ((@portfolio_value_change_24h * 100) / @portfolio_value).round(2).delimited(delimiter = ',') %>%
        (+<%= @portfolio_value_change_24h.round(2).delimited(delimiter = ',') %> €)
      </div>
    <% elsif @portfolio_value_change_24h < 0 %>
      <div class="text-danger">
        - <%= (((@portfolio_value_change_24h * 100) / @portfolio_value).round(2) * -1).delimited(delimiter = ',') %>%
        (<%=  @portfolio_value_change_24h.round(2).delimited(delimiter = ',') %> €)
      </div>
    <% end %>
    </div>
  </div>
</div>

<!-- print crypto name / current value / allocation / wallet name / number of cryptos / value -->
<div class="container mb-3">
  <div class="card-portfolio-separate-header">
    <div class="card-portfolio-separate-header-first">
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          ACCOUNT
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          PRICE
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          ALLOCATION
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          WALLET
        </div>
      </div>
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          AMOUNT
        </div>
      </div>
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          VALUE
        </div>
      </div>
    </div>
  </div>

  <% @portfolio_rows.each do |row| %>
  <div class="card-portfolio-separate">
      <div class="card-portfolio-box-separate">
        <div class="">
          <div class="pb-1">
            <%= image_tag row[:image], class: "logo-crypto-small" %>
          </div>
        <%= row[:account] %>
        </div>
      </div>
      <div class="card-portfolio-box-separate d-none d-md-block">
        € <%= row[:current_price].delimited(delimiter = ',') %>
      </div>
      <div class="card-portfolio-box-separate d-none d-md-block">
        <div>
          <%= row[:allocation].round(2).delimited(delimiter = ',') %> %
        </div>
      </div>
      <div class="card-portfolio-box-separate d-none d-md-block">
        <div>
          <%= row[:wallet_name] %>
        </div>
      </div>
      <div class="card-portfolio-box-separate">
        <div>
          <%= row[:number].delimited(delimiter = ',') %> <%= row[:symbol].upcase %>
        </div>
      </div>
      <div class="card-portfolio-box-separate">
        <div>
          € <%= row[:value].round(2).delimited(delimiter = ',') %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="container mb-4">
  <% @portfolio_rows.each do |row| %>
          <% if row[:number] > 0 %>
          <% value = 3.5 %>
          <% width = row[:allocation].round(0) * 3.5 %>
            <% bar = content_tag :div, '', style: "width: #{width}px; height: 10px; background-color: #746e9e; border-top-left-radius: 4px; border-bottom-left-radius: 4px;" %>
            <% bar2 = content_tag :div, '', style: "width: #{(value * 100) - width}px; height: 10px; background-color: #3c3c3c; border-top-right-radius: 4px; border-bottom-right-radius: 4px;" %>
        <div class="ms-4">
          <div class="d-flex">
            <div>
            <%= row[:account] %>
            </div>
          </div>
            <div class="color-pourcentage">
            <%= row[:allocation].round(2) %>%
            </div>
          <div class="d-flex mb-3">
            <%= bar %>
            <%= bar2 %>
          </div>
        </div>
          <% end %>
  <% end %>
</div>

<!-- link to add a new wallet  -->
<div class="container d-flex mb-5">
  <div class="pt-2">
    <%= link_to "Add Wallet", new_wallet_path(@wallet), class: "dark-grey-button"%>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-container justify-content-around ps-2 pe-2">
  <div class="pt-4">
    <%= link_to "GitHub", "https://github.com/PierreAnders/", class: "external-link logo-github", :target => "_blank" %>
  </div>
  <div class="pt-4">
    <%= link_to "CoinGecko", "https://www.coingecko.com/", class: "external-link logo-github", :target => "_blank" %>
  </div>
  <div class="pt-4">
    <%= link_to "Rarible", "https://rarible.com/", class: "external-link logo-github", :target => "_blank" %>
  </div>
  <div class="pt-4">
    <%= link_to "Metamask", "https://metamask.io/", class: "external-link logo-github", :target => "_blank" %>
  </div>
  <div class="pt-4">
    <%= link_to "Etherscan", "https://etherscan.io/", class: "external-link logo-github", :target => "_blank" %>
  </div>
  <div class="pt-4">
    <%= link_to "Privacy", privacy_path, class: "external-link logo-github" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div style="background-color: #1D1D1D" class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="logo">
        <%= image_tag "logo.png" %>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "PORTFOLIO", portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "MARKET", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "SEND", transfers_new_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "TRANSACTIONS", transfers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "NFTs", nft_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "WALLETS", wallets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "LOG OUT", destroy_user_session_path(), method: :delete, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "MARKET", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "PORTFOLIO", portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "NFTs", nft_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "WALLETS", wallets_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transfers/index.html.erb
<!-- Form to choose one of the user's ethereum addresses-->
<div class="container mb-3">
  <div class="form-container">
  <h1 class="mb-5">TRANSACTIONS</h1>
    <div class="container-portfolio mb-5">
      <div class="d-flex justify-content-center">
          <%= form_with url: transfers_path, method: :get do |form| %>
        <div class="m-2">
          <%= form.select :query, @address_option, include_blank: "select address", class: "form-button-input" %>
        </div>
        <div class="d-flex justify-content-end m-2">
          <%= form.submit "Search", class: "grey-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

  <!-- If an address is selected then display the associate transactions -->
  <div class="form-container">
  <% if params[:query].present? %>
  <div class="container-portfolio mb-5">
    <h3 class="mb-3">ETHEREUM ADDRESS :</h3>
    <%= params[:query] %>
  </div>
    <% @transactions.reverse_each do |transaction| %>
    <div class="container-portfolio mb-5">
      <p class="color-medium-grey">Date: </p><p> <%= Time.at(transaction['timeStamp'].to_i).strftime("%d/%m/%Y %H:%M:%S") %></p>
      <p class="color-medium-grey">From: </p><p><%= transaction['from'] %></p>
      <p class="color-medium-grey">To: </p><p><%= transaction['to'] %></p>
      <p class="color-medium-grey">Amount: </p><p> <%= (transaction['value'].to_f / 10**18).round(18) %> ETH</p>
    </div>
    <% end %>
  <% end %>
</div>

app/views/wallets/index.html.erb
<div class="form-container">
  <h1>WALLETS</h1>
  <% @total_wallet_value = 0 %>
  <!-- print wallet name / category / number of cryptos / value -->
  <% @wallets.each do |wallet| %>
    <%= link_to wallet_path(wallet) do %>
      <div class="form-cellule mt-5">
        <div class="mt-2 form-title">
          <%= wallet.name %>
        </div>
        <div class="d-flex justify-content-between">
          <div class="ms-3 me-3 mb-1 color-medium-grey">
            <%=  wallet.cryptos.size %> cryptos
          </div>
          <!-- get cryptos details value -->
          <% wallet.cryptos.each do |crypto| %>
            <!-- get crypto current price with API -->
            <% @search_cryptos.each do |search_crypto| %>
              <% if crypto.name == search_crypto["name"] %>
                <% @crypto_current_price = search_crypto["current_price"] %>
              <% end %>
            <% end %>
            <!-- puts wallet value -->
            <% @total_crypto_value = crypto.number * @crypto_current_price %>
            <% @total_wallet_value = @total_wallet_value + @total_crypto_value %>
          <% end %>
          <div class="ms-3 me-3 color-medium-grey">
            € <%= @total_wallet_value.round(2).delimited(delimiter = ' ', separator = ',') %>
          </div>
        </div>
        <% @total_wallet_value = 0 %>
      </div>
    <% end %>
  <% end %>
  <div class="d-flex m-3">
    <%= link_to "add wallet", new_wallet_path(@wallet), class: "dark-grey-button"  %>
  </div>
</div>

app/views/wallets/show.html.erb
<!-- print wallet value and change 24h -->
<div class="container mb-3">
  <div class="container container-portfolio mb-4">
    <div class="card-cryptos-details">
      <h1 class="m-2">€ <%= @wallet_value.round(2).delimited(delimiter = ',') %></h1>
      <h2 class="m-2"><%= @wallet.name.upcase %> (<%= @wallet.cryptos.size %>)</h2>
    </div>
    <div class="m-2 color-medium-grey">
      Total balance
    </div>
    <div class="m-2" >
      <% if @wallet_value_change_24h > 0 %>
        <div class="text-success">
          + <%= ((@wallet_value_change_24h * 100) / @wallet_value).round(2).delimited(delimiter = ',') %>%
          (+<%= @wallet_value_change_24h.round(2).delimited(delimiter = ',') %> €)
        </div>
      <% elsif @wallet_value_change_24h < 0 %>
        <div class="text-danger">
          - <%= (((@wallet_value_change_24h * 100) / @wallet_value).round(2) * -1).delimited(delimiter = ',') %>%
          (<%=  @wallet_value_change_24h.round(2).delimited(delimiter = ',') %> €)
        </div>
      <% end %>
    </div>
  </div>

  <!-- print wallet portfolio -->
  <div class="container container-portfolio">
    <div class="card-portfolio-header">
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          Account
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          Price
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          Allocation
        </div>
      </div>
      <div class="card-portfolio-box d-none d-md-block">
        <div class="color-medium-grey">
          Address
        </div>
      </div>
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          Amount
        </div>
      </div>
      <div class="card-portfolio-box">
        <div class="color-medium-grey">
          Value
        </div>
      </div>
    </div>
    <% @wallet_rows.each do |row| %>
      <div class="card-portfolio">
        <div class="card-portfolio-box">
          <div class="">
            <div class="pb-1">
              <%= link_to (image_tag row[:image], class: "logo-crypto-small"), edit_wallet_crypto_path(@wallet, row[:crypto]) %>
            </div>
            <%= link_to "#{row[:account]}", edit_wallet_crypto_path(@wallet, row[:crypto]), class: "crypto-link" %>
          </div>
        </div>
        <div class="card-portfolio-box d-none d-md-block">
          <div>
            € <%= row[:current_price].round(2).delimited(delimiter = ',') %>
          </div>
        </div>
        <% row%>
        <div class="card-portfolio-box d-none d-md-block">
          <div>
            <%= row[:allocation].round(2).delimited(delimiter = ',') %> %
          </div>
        </div>
        <div class="card-portfolio-box d-none d-md-block">
          <div>
            <%= row[:address].first(3) %>...<%= row[:address].last(3) %>
          </div>
        </div>
        <div class="card-portfolio-box">
          <div>
            <%= row[:number].delimited(delimiter = ',') %> <%= row[:symbol].upcase %>
          </div>
        </div>
        <div class="card-portfolio-box">
          <div>
            € <%= row[:value].round(2).delimited(delimiter = ',') %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="container d-flex">
    <div class="p-2 mt-3">
      <%= link_to "Edit Wallet", edit_wallet_path(@wallet), class: "dark-grey-button"%>
    </div>
    <div class="p-2 mt-3">
      <%= link_to "Back to wallets", wallets_path(@wallets), class: "small-button" %>
    </div>
  </div>
  <div class="form-container mt-5 mb-5">
    <h2>ADD NEW CRYPTO</h2>
    <%= form_with model: [@wallet, @crypto] do |f| %>
      <div class="form-cellule mt-5">
        <%= f.text_field :account, placeholder: "Account", class: "form-button-input" %>
      </div>
      <div class="form-cellule mt-5">
        <div class="form-button-input">
          <%= f.select :name, @select_cryptos, include_blank: "select crypto" %>
        </div>
      </div>
      <div class="form-cellule mt-5">
        <%= f.text_field :address, placeholder: "Address", class: "form-button-input" %>
      </div>
      <div class="form-cellule mt-5">
        <%= f.number_field :number, placeholder: "    Amount", :step => 0.00000001, class: "form-button-input" %>
      </div>
      <div>
        <%= f.submit "Add crypto", class: "grey-button"%>
      </div>
    </div>
  <% end %>
</div>